---
- name: Update package cache
  ansible.builtin.package:
    update_cache: yes
    
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Start and enable Nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
